# Source import
import graph


# Pakage import
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QCoreApplication
from PyQt5 import QtCore, QtGui, QtWidgets
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import FigureCanvasQT as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FireUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtWidgets.QMainWindow):
    def __init__(self) :
        super().__init__()
        self.setupUi(self)
        # SetUI initial
        # self.initUI()


    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(483, 704)
        Dialog.setMinimumSize(QtCore.QSize(0, 704))
        self.groupBox_FILE = QtWidgets.QGroupBox(Dialog)
        self.groupBox_FILE.setGeometry(QtCore.QRect(21, 160, 439, 91))
        self.groupBox_FILE.setTitle("")
        self.groupBox_FILE.setObjectName("groupBox_FILE")
        self.labelgetFile2 = QtWidgets.QLabel(self.groupBox_FILE)
        self.labelgetFile2.setGeometry(QtCore.QRect(80, 50, 300, 16))
        self.labelgetFile2.setText("")
        self.labelgetFile2.setObjectName("labelgetFile2")
        self.label_FILE2 = QtWidgets.QLabel(self.groupBox_FILE)
        self.label_FILE2.setGeometry(QtCore.QRect(30, 50, 34, 16))
        self.label_FILE2.setObjectName("label_FILE2")
        self.label_FILE1 = QtWidgets.QLabel(self.groupBox_FILE)
        self.label_FILE1.setGeometry(QtCore.QRect(30, 20, 34, 16))
        self.label_FILE1.setObjectName("label_FILE1")
        self.labelgetFile1 = QtWidgets.QLabel(self.groupBox_FILE)
        self.labelgetFile1.setGeometry(QtCore.QRect(80, 20, 300, 16))
        self.labelgetFile1.setText("")
        self.labelgetFile1.setObjectName("labelgetFile1")
        self.groupBox_GRAPH = QtWidgets.QGroupBox(Dialog)
        self.groupBox_GRAPH.setGeometry(QtCore.QRect(20, 320, 441, 371))
        self.groupBox_GRAPH.setTitle("")
        self.groupBox_GRAPH.setObjectName("groupBox_GRAPH")
        self.widget_GRAPH = QtWidgets.QWidget(self.groupBox_GRAPH)
        self.widget_GRAPH.setGeometry(QtCore.QRect(10, 20, 421, 341))
        self.widget_GRAPH.setObjectName("widget_GRAPH")
        self.groupBox_COR = QtWidgets.QGroupBox(Dialog)
        self.groupBox_COR.setGeometry(QtCore.QRect(20, 260, 441, 51))
        self.groupBox_COR.setTitle("")
        self.groupBox_COR.setObjectName("groupBox_COR")
        self.label_COE = QtWidgets.QLabel(self.groupBox_COR)
        self.label_COE.setGeometry(QtCore.QRect(10, 20, 48, 16))
        self.label_COE.setObjectName("label_COE")
        self.label = QtWidgets.QLabel(self.groupBox_COR)
        self.label.setGeometry(QtCore.QRect(60, 20, 56, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_REL = QtWidgets.QLabel(self.groupBox_COR)
        self.label_REL.setGeometry(QtCore.QRect(200, 20, 48, 16))
        self.label_REL.setObjectName("label_REL")
        self.label_2 = QtWidgets.QLabel(self.groupBox_COR)
        self.label_2.setGeometry(QtCore.QRect(250, 20, 56, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 441, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_SEL_FILE = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_SEL_FILE.setTitle("")
        self.groupBox_SEL_FILE.setObjectName("groupBox_SEL_FILE")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_SEL_FILE)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnLOADFILE1 = QtWidgets.QPushButton(self.groupBox_SEL_FILE)
        self.btnLOADFILE1.setObjectName("btnLOADFILE1")
        self.verticalLayout_2.addWidget(self.btnLOADFILE1)
        self.btnLOADFILE2 = QtWidgets.QPushButton(self.groupBox_SEL_FILE)
        self.btnLOADFILE2.setObjectName("btnLOADFILE2")
        self.verticalLayout_2.addWidget(self.btnLOADFILE2)
        self.comboBoxAREA = QtWidgets.QComboBox(self.groupBox_SEL_FILE)
        self.comboBoxAREA.setObjectName("comboBoxAREA")
        self.comboBoxAREA.addItem("")
        self.verticalLayout_2.addWidget(self.comboBoxAREA)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.groupBox_SEL_FILE)
        self.groupBox_OPT = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_OPT.setTitle("")
        self.groupBox_OPT.setObjectName("groupBox_OPT")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_OPT)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 81, 111))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_CURVED = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_CURVED.setObjectName("radioButton_CURVED")
        self.verticalLayout.addWidget(self.radioButton_CURVED)
        self.radioButton_DISTRIBUTED = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioButton_DISTRIBUTED.setObjectName("radioButton_DISTRIBUTED")
        self.verticalLayout.addWidget(self.radioButton_DISTRIBUTED)
        self.checkBox_TREND = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_TREND.setObjectName("checkBox_TREND")
        self.verticalLayout.addWidget(self.checkBox_TREND)
        self.horizontalLayout.addWidget(self.groupBox_OPT)
        self.groupBox_RUN = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_RUN.setTitle("")
        self.groupBox_RUN.setObjectName("groupBox_RUN")
        self.btn_RUN = QtWidgets.QPushButton(self.groupBox_RUN)
        self.btn_RUN.setGeometry(QtCore.QRect(-2, -10, 111, 161))
        self.btn_RUN.setObjectName("btn_RUN")
        self.horizontalLayout.addWidget(self.groupBox_RUN)
        self.groupBox_LOGO = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_LOGO.setTitle("")
        self.groupBox_LOGO.setObjectName("groupBox_LOGO")
        self.label_LOGO = QtWidgets.QLabel(self.groupBox_LOGO)
        self.label_LOGO.setGeometry(QtCore.QRect(0, 10, 91, 121))
        self.label_LOGO.setObjectName("label_LOGO")
        self.horizontalLayout.addWidget(self.groupBox_LOGO)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btnLOADFILE1, self.btnLOADFILE2)
        Dialog.setTabOrder(self.btnLOADFILE2, self.comboBoxAREA)
        Dialog.setTabOrder(self.comboBoxAREA, self.radioButton_CURVED)
        Dialog.setTabOrder(self.radioButton_CURVED, self.radioButton_DISTRIBUTED)
        Dialog.setTabOrder(self.radioButton_DISTRIBUTED, self.checkBox_TREND)
        Dialog.setTabOrder(self.checkBox_TREND, self.btn_RUN)

        # 파일1 선택 선언
        self.btnLOADFILE1.clicked.connect(self.initbtnLOADFILE1)
        #파일2 선택 선언
        self.btnLOADFILE2.clicked.connect(self.initbtnLOADFILE2)

        self.initUI()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_FILE2.setText(_translate("Dialog", "파일2:"))
        self.label_FILE1.setText(_translate("Dialog", "파일1:"))
        self.label_COE.setText(_translate("Dialog", "상관계수"))
        self.label_REL.setText(_translate("Dialog", "상관관계"))
        self.btnLOADFILE1.setText(_translate("Dialog", "첫번째 파일"))
        self.btnLOADFILE2.setText(_translate("Dialog", "두번째 파일"))
        self.comboBoxAREA.setItemText(0, _translate("Dialog", "지역선택"))
        self.radioButton_CURVED.setText(_translate("Dialog", "꺾은선"))
        self.radioButton_DISTRIBUTED.setText(_translate("Dialog", "분산형"))
        self.checkBox_TREND.setText(_translate("Dialog", "추세선"))
        self.btn_RUN.setText(_translate("Dialog", "분석 실행"))
        self.label_LOGO.setText(_translate("Dialog", "TextLabel"))

    # addUI initial
    def initUI(self):
        self.setWindowTitle('Fire')
        self.setWindowIcon(QIcon('icon.png'))
        self.initSTATUS()
        self.initMENU()

    # StatusBar initial
    def initSTATUS(self):
        self.statusBar().showMessage('Ready')

    # MenuBar initial
    def initMENU(self):
        exitAction = QAction('Exit', self)
        exitAction.setShortcut('Ctrl+Q')
        exitAction.triggered.connect(QCoreApplication.instance().quit)

        menubar = self.menuBar()
        menubar.setNativeMenuBar(False)
        filemenu = menubar.addMenu('&File')
        filemenu.addAction(exitAction)

    def initbtnLOADFILE1(self):
        global fname1
        fname1 = QFileDialog.getOpenFileName(self, '', '', 'All File(*);; Exel Data(*.csv)')
        self.labelgetFile1.setText(fname1[0])


    def initbtnLOADFILE2(self):
        global fname2
        fname2 = QFileDialog.getOpenFileName(self, '', '', 'All File(*);; Exel Data(*.csv)')
        self.labelgetFile2.setText(fname2[0])



if __name__ == "__main__" :
    app = QApplication(sys.argv)
    Main = QMainWindow()
    ui = Ui_Dialog()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())